### ISSUE TITLE
[BUG] Set default values of "Multiplier" tab to 1 instead of 0

### ISSUE THREAD

**Issue by SeahDokki** [JensvandeWiel/ArkAscendedServerManager#133]
**Describe the bug**
With the new Multiplier tab update, the manager will override GameUserSettings.ini, but all the values are set to 0 by default.
It cause a lot of trouble if user are not paying attention.

**To Reproduce**
1. Update ASAM
2. Start the server without editing Multiplier tab
3. GameUserSettings.ini & Game.ini will have all their integer values set to 0

**Expected behavior**
Multiplier tab should have default value matching ARK:SA official servers ratings

**Screenshots**
- No Screenshot
- 
**Desktop (please complete the following information):**
 - OS: Windows Server 22
 - App Version: 1.0.0

**Comment by dtm85** [comment]
I noticed the same thing, this new 0.1.0 update will overwrite all the "Game.ini" and "GameUserSettings.ini" this shouldn't happen, it should in fact read the settings from the ini first and import them to the UI interface not make you have to configure them all over again. Not to mention it will overwrite it every time.

I did notice that there's and option to read the settings from the ini and not the JSON but why does that say "Not recommended"?

**Comment by JensvandeWiel** [comment]
Its not recommended because you should set the settings trough the app for intended behaviour, as for the 1 to 0 values, this is because the olde servers created before v01.0 don't have the gus and game settings in the json, that is why when you use an existing server they all get set to 0 or false.

This is not nice, but at this time we cannot do anything about it, it is recommended to make a new server or enable use ini config
